apiVersion: ai.manager.io/v1alpha1
kind: Endpoint
metadata:
  labels:
    app.kubernetes.io/name: endpoint
    app.kubernetes.io/instance: endpoint-sample
    app.kubernetes.io/part-of: ai-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ai-manager
  name: endpoint-sample
spec:
  # TODO(user): Add fields here
