apiVersion: ai.manager.io/v1alpha1
kind: AssembledModel
metadata:
  labels:
    app.kubernetes.io/name: assembledmodel
    app.kubernetes.io/instance: assembledmodel-sample
    app.kubernetes.io/part-of: ai-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ai-manager
  name: assembledmodel-sample
spec:
  # TODO(user): Add fields here
