apiVersion: ai.manager.io/v1alpha1
kind: Inference
metadata:
  labels:
    app.kubernetes.io/name: inference
    app.kubernetes.io/instance: inference-sample
    app.kubernetes.io/part-of: ai-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ai-manager
  name: inference-sample
spec:
  # TODO(user): Add fields here
